### ISSUE TITLE
Include an external project setup snippet in readme

### ISSUE THREAD

**Issue by IvantheTricourne** [f-o-a-m/kepler#202]
We should consider including a "how to make your own hs-abci project" walkthrough. This is separate and different from the existing `nameservice` tutorial. This should be more general and allow people to understand how to setup their own abci apps outside (unlike `nameservice`) of this repo:

1. What is the proper way import _this_ repo (i.e., the proper way to use this repo as a library)?
2. Should external projects import individual libraries in this repo (i.e., `hs-abci-sdk`, `hs-abci-server`, `hs-abci-types`)?

**Comment by IvantheTricourne** [comment]
This was quite useful: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages

**Comment by IvantheTricourne** [comment]
In an external project, I've done this with the following in a `stack.yaml` file:

```yaml
extra-deps:
  - git: https://github.com/f-o-a-m/hs-abci/
    commit: 3b13a569bcc77dcdec154552175f69bf4ea8b8ca
    subdirs:
      - hs-abci-extra
      - hs-abci-sdk
      - hs-abci-server
      - hs-abci-test-utils
      - hs-abci-types
      - hs-tendermint-client
```
